# Name of your application. Used to uniquely configure containers.
service: kurir

# Name of the container image.
image: cfarvidson/kurir

# Deploy to these servers.
servers:
  web:
    hosts:
      - kurir-app-1.banded-beta.ts.net
    options:
      memory: 2048m

proxy:
  app_port: 3000
  healthcheck:
    path: /api/up

# Credentials for your image host.
registry:
  server: docker-registry.banded-beta.ts.net
  username:
    - DOCKER_REGISTRY_TOKEN
  password:
    - DOCKER_REGISTRY_TOKEN

# Configure builder setup.
builder:
  arch: amd64
  dockerfile: ./Dockerfile
  context: .

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    NODE_ENV: production
    WEBAUTHN_RP_NAME: Kurir
    WEBAUTHN_RP_ID: kurir-app-1.banded-beta.ts.net
    NEXTAUTH_URL: https://kurir-app-1.banded-beta.ts.net
  secret:
    - DATABASE_URL
    - NEXTAUTH_SECRET
    - ENCRYPTION_KEY
    - POSTGRES_PASSWORD

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: postgres:16-alpine
    host: kurir-database-1.banded-beta.ts.net
    port: 5432
    env:
      clear:
        POSTGRES_DB: kurir
        POSTGRES_USER: kurir
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
