import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

/**
 * Internal callback used by the kurir-updater sidecar to report update
 * progress. Authenticated with the shared UPDATER_TOKEN env var — the token
 * is generated by install.sh and passed into both the app and the updater
 * container. Without that token set, this endpoint refuses all requests
 * (previously it was unauthenticated, which let anyone poison UpdateLog rows
 * just by guessing an id).
 */
export async function POST(request: NextRequest) {
  const expected = process.env.UPDATER_TOKEN;
  if (!expected) {
    return NextResponse.json(
      { error: "Updater not configured" },
      { status: 503 },
    );
  }

  const presented = request.headers.get("x-updater-token");
  if (presented !== expected) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json().catch(() => null);
  if (!body || typeof body !== "object") {
    return NextResponse.json({ error: "Invalid body" }, { status: 400 });
  }

  const { logId, status, error } = body as {
    logId?: string;
    status?: string;
    error?: string | null;
  };

  if (!logId || !status) {
    return NextResponse.json(
      { error: "Missing logId or status" },
      { status: 400 },
    );
  }

  const log = await db.updateLog.findUnique({ where: { id: logId } });
  if (!log) {
    return NextResponse.json({ error: "Unknown log ID" }, { status: 404 });
  }

  const now = new Date();
  const durationMs = now.getTime() - log.createdAt.getTime();
  const terminal = ["success", "failed", "rolled_back"].includes(status);

  await db.updateLog.update({
    where: { id: logId },
    data: {
      status,
      error: error ?? null,
      durationMs: terminal ? durationMs : log.durationMs,
      completedAt: terminal ? now : log.completedAt,
    },
  });

  return NextResponse.json({ ok: true });
}
